name: project-application
title: form.application.title
description: form.application.description
delivery:
  - channel: email
    destination: ["${contact.default}"]
# Resubmittable means you can start over at the end, possibly with carry-over details.
resubmittable:
  start: contactInfo
  alert:
    title: You started over!
    description: You can continue, we saved some of the details from earlier.
  fields:
    - contactInfo.fullName
    - contactInfo.email
    - contactInfo.phone
    - organizationInfo.organizationName
    - organizationInfo.organizationNumber
    - organizationInfo.organizationAddressStreet
    - organizationInfo.organizationAddressCo
    - organizationInfo.organizationAddressPostcode
    - organizationInfo.organizationAddressCity
    - organizationInfo.accountableParties
    - organizationInfo.organizationEmail
    - organizationInfo.organizationPhone
    - organizationAbout.organizationAbout
    - organizationAbout.organizationWebsite
    - organizationAbout.organizationFacebook
    - organizationAbout.organizationInstagram
    - organizationAbout.organizationTikTok
    - organizationAbout.organizationYouTube
    - organizationAbout.organizationLinkedIn
    - financialInfo.bankName
    - financialInfo.regNr
    - financialInfo.accountNumber
    - financialInfo.financialPatrons
    - branding.logo

# Receipt to the submitter.
receipts:
  - channel: email
    destination: ["${form.contactInfo.email}", "${form.organizationInfo.organizationEmail}"]
    subject:
      da: Vi har modtaget din søknad
      en: We have received your application
    body:
      en: |
        ### Application received
        Thank you for your application for Frigear Funding.
        
        We will get back to you as soon as possible.
        
        In the meantime, you can find more information on our website: [frigear.nu/en/funding](https://frigear.nu/en/funding)