import { defineNuxtModule, createResolver } from '@nuxt/kit'
import fs from 'node:fs/promises'
import path from 'node:path'
import { parse } from '@vue/compiler-sfc'

export interface ModuleOptions {
  emailsDir?: string
  outputFile?: string
}

const name = 'generate-email-types'

export default defineNuxtModule<ModuleOptions>({
  meta: { name },
  defaults: {
    emailsDir: 'shared/emails',
    outputFile: 'types/email-props.generated.d.ts', // relative to buildDir now
  },
  async setup(options, nuxt) {
    if (!nuxt.options.dev) {
      console.log('Skipping email types generation when not in dev mode.')
      return
    }

    const { resolve } = createResolver(import.meta.url)

    const emailsDir = resolve(nuxt.options.rootDir, options.emailsDir!)
    const outputFile = resolve(nuxt.options.buildDir, options.outputFile!)

    // Recursively scan .vue files
    async function scanVueFiles(dir: string): Promise<string[]> {
      const entries = await fs.readdir(dir, { withFileTypes: true })
      const files: string[] = []
      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name)
        if (entry.isDirectory()) files.push(...(await scanVueFiles(fullPath)))
        else if (entry.isFile() && entry.name.endsWith('.vue')) files.push(fullPath)
      }
      return files
    }

    const vueFiles = await scanVueFiles(emailsDir)
    let output = `// Generated by ${name}\n\n`

    for (const file of vueFiles) {
      const content = await fs.readFile(file, 'utf-8')
      const { descriptor } = parse(content)
      if (!descriptor.scriptSetup) continue

      const script = descriptor.scriptSetup.content

      // Match defineProps with inline type
      let propsType = 'any'
      const match = script.match(/defineProps<([\s\S]*?)>\(\)/)
      if (match) {
        // @ts-expect-error we allow this
        propsType = match[1].trim()
      }

      // Make path match Nuxt alias
      const aliasPath = '#shared/emails/' + path.relative(emailsDir, file).replace(/\\/g, '/')

      output += `declare module '${aliasPath}' {\n`
      output += `  import { DefineComponent } from 'vue'\n`
      output += `  const component: DefineComponent<${propsType}, any, any>\n`
      output += `  export default component\n`
      output += `  export type Props = typeof component extends DefineComponent<infer P, any, any> ? P : never\n`
      output += `}\n\n`
    }

    await fs.mkdir(path.dirname(outputFile), { recursive: true })
    await fs.writeFile(outputFile, output, 'utf-8')

    // Make TS aware of the generated types
    if (!nuxt.options.typescript.hoist.includes(outputFile)) {
      nuxt.options.typescript.hoist.push(outputFile)
    }
    nuxt.options.typescript.tsConfig ||= {}
    nuxt.options.typescript.tsConfig.include ||= []
    nuxt.options.typescript.tsConfig.include.push(outputFile)

    console.log(`✅ Generated email props types for ${vueFiles.length} components at ${outputFile}`)
  },
})
