name: CI

on:
  pull_request:
    branches:
      - main
      - staging

env:
  NODE_OPTIONS: --max-old-space-size=8192
  NITRO_PRESET: ${{ vars.NITRO_PRESET }}
  STUDIO_GITHUB_CLIENT_SECRET: ${{ secrets.STUDIO_GITHUB_CLIENT_SECRET }}
  STUDIO_GITHUB_CLIENT_ID: ${{ vars.STUDIO_GITHUB_CLIENT_ID }}

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.6
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
    env:
      NITRO_PRESET: node-server
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.6
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Test
        run: pnpm test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ !cancelled() }}
        with:
          files: test-results/junit.xml
